### PR TITLE
update with klaytn v1.10.2

### PR DESCRIPTION
**Pull request by JayChoi1736**
Fixes # .
- update klaytn version to v1.10.2 
- fix broken github action due to golang version
- add codeowners

### CODE REVIEW

**Comment by kjeom** [comment]
@JayChoi1736 Can you add me in the code owners?

**Comment by kjeom** [comment]
Please add you in the owners as well

**Comment by JayChoi1736** [comment]
> Please add you in the owners as well
Done. :)

and also fixed github action

**Comment by JayChoi1736** [comment]
@reveiwers please take a look

**Review by kjeom — APPROVED** [review]

**Pull request merged**
