### PR TITLE
Applied dynamic gas pricing and burning mechanism 

### PR DESCRIPTION
**Pull request by jimni1222**
This PR introduces appliance of dynamic gas pricing and burning mechanism for Magma hard fork.

From Magma hard fork, Klaytn will burn half of the transaction fee.
Also depends on base fee, we need to decide what to use between `gasPrice` and `baseFee` when calculate transaction fee.

I will update Klaytn version when Klaytn release v1.9.0

### CODE REVIEW

**Comment by kjhman21** [comment]
Don't we need to change KIP71 to Magma?

**Comment by jimni1222** [comment]
This test will be failed until Klaytn version is updated.

**Comment by jimni1222** [comment]
@kjhman21 I added [a commit](https://github.com/klaytn/rosetta-klaytn/pull/115/commits/e2bb2d7cc47b70c5bc511cb34f61d8140b5af680) separately for main logic.
You can take a look https://github.com/klaytn/rosetta-klaytn/pull/115/commits/e2bb2d7cc47b70c5bc511cb34f61d8140b5af680 mainly.
The others are test data or READMD modification.

**Review by kjhman21 — APPROVED** [review]
LGTM

**Comment by jimni1222** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
